# Generated by Django 2.0.2 on 2018-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('timein', models.DateTimeField(auto_now_add=True)),
                ('timeout', models.DateTimeField()),
            ],
        ),
    ]
